ratings:
  namespace: student14-bookinfo-uat
  image: ghcr.io/supakkavee/bookinfo-ratings
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student14/ratings(/|$)(.*)"
  serviceType: ClusterIP

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
  COMMIT_SHA: CHANGEME
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-uat-ratings-mongodb-secret: mongodb-password
  MONGO_ROOT_PASSWORD:
    bookinfo-uat-ratings-mongodb-secret: mongodb-root-password