ratings:
  namespace: student14-bookinfo-dev
  image: ghcr.io/supakkavee/bookinfo-ratings
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student14/ratings(/|$)(.*)"
  serviceType: ClusterIP

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-dev-ratings-mongodb-secret: mongodb-password
  MONGO_ROOT_PASSWORD:
    bookinfo-dev-ratings-mongodb-secret: mongodb-root-password